### ISSUE TITLE
[8pt] Leveed area being inundated by branch

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1021]
HUC `01080205` branch `7703000014` is inundating behind a levee system in Hartford, CT.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/c034a5f9-b6f5-497b-82e9-ffd8f3e5efa6)

**Comment by mluck** [comment]
`src/mask_dem.py` has been modified so that a levelpath that crosses through a levee-protected area is only able to inundate the levee-protected area within the catchment of the levelpath (not the entire levee-protected area). Compared with the initial image in this issue, the image below shows branch inundation only within the levelpath catchment (highlighted in yellow), resulting in much less inundation in the levee-protected area. Note that the levee-protected areas upstream of the levelpath are completely masked as they are outside of the levelpath catchment, but this is consistent with the fact that we mask branch 0. Inundation is based on 100yr recurrence flows.
<img width="471" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/b035156f-06f3-4d8d-82d2-fe7f4e431f8f">

A closer view of the branch inundation (blue) in the levelpath catchment (yellow) in the levee-protected area (dotted).
<img width="471" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/8941a0f3-facb-4bfc-a180-3224cb06d74c">
