### ISSUE TITLE
[3pt] OpenJDK vulnerability

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1105]
Installed version: 17.0.8
Fixed version: Upgrade to a version greater than 17.0.9

**Comment by mluck** [comment]
I tested upgrading GDAL from v3.8.0 to v3.8.4 and that upgraded OpenJDK from 17.0.8 to 17.0.9; however, that does not fulfill the requirement for a JDK version > 17.0.9. Neither did adding `openjdk-21-jre` to the Dockerfile:
```
RUN apt-get update --fix-missing && apt-get install -y cmake mpich \
    libgtest-dev libboost-test-dev libnetcdf-dev openjdk-21-jre && rm -rf /var/lib/apt/lists/*
```

@RobHanna-NOAA Can you figure out a solution for upgrading JDK that doesn't depend on the JDK version installed with GDAL? Otherwise we may need to do something like fork the [GDAL Dockerfile](https://github.com/OSGeo/gdal/blob/master/docker/ubuntu-full/Dockerfile) and amend the `JAVA_VERSION=17` set there.

**Comment by RobHanna-NOAA** [comment]
Loaded the fix into UCS2 and had ITSG check it. All fixed. I will get a PR info it and merged. :)
