### ISSUE TITLE
Bad crosswalks along the Brazos River 12070104

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#1194]
Feedback from Katie Laundry that there was some ugly overestimated FIM along the Brazos River near Brazoria, TX (12070104). After a quick review I noted erroneous crosswalks in branch 0. The screenshot below is highlighting numerous hydroids (tan catchments) that are being incorrectly crosswalked to the mainstem Brazos River (red featureid segment) rather than the small tributary that transects these catchments (green featureid segment). 

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/69868854/7a106989-c589-47fd-a40b-212e72e30335)

The blue inundation shown is the 2yr NWM inundation. Note that there are likely additional crosswalking issues in this region.

**Comment by RyanSpies-NOAA** [comment]
@mluck @derekgiardino tagging for awareness

**Comment by mluck** [comment]
Crossreferencing to #1190

**Comment by CarsonPruitt-NOAA** [comment]
Yeah, this is pretty terrible crosswalking. And, it's not really our fault because the NWM catchments don't really match the streamlines. The red outline shows the NWM catchment that encompasses both the Brazos and it's 1st-order tributary. When we crosswalk via the midpoint method, we're picking the Brazos feature_id every time.

Matt is going to cringe at me saying this, but I'm wondering if we should switch up our crosswalking to snap the midpoints to NWM streamlines instead of doing an sjoin on the NWM catchments...

**Comment by CarsonPruitt-NOAA** [comment]
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/04e04673-b1ec-44ff-aee1-c35bde5eea45)

**Comment by derekgiardino** [comment]
Would this stem back to the original catchments developed in hydrofabric, should we share it with Mike and that team to see if the catchment redesign may fix these types of issues, or if we should chase other solutions

**Comment by CarsonPruitt-NOAA** [comment]
Yes, this could be fixed in the hydrofabric if the 1st-order tributaries on both sides of the Brazos had their own catchments. We could potentially identify everywhere this particular problem is occurring because the ratio of NWM streamlines to catchments won't be 1:1.
