### ISSUE TITLE
[3pt] Investigate line ending differences in developers' local repos

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#121]
It has been observed that line endings differ between developers' local repos. While this is not an issue for FIM performance, I wanted to document it.

**Comment by BradfordBates-NOAA** [comment]
@BrianAvant-NOAA Please feel free to add your observations to this ticket.

**Comment by nickchadwick-noaa** [comment]
This is probably due to your specific Git settings on your computer. Take at look at this page to see how to configure these settings https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings

I think by default Git will convert things to LF when your push, but it will keep things as CRLF on your local copy (if the original format is CRLF).

From my experience with the VMs, when I create a file on the VM (with like "touch somefile.py") and then open it on a code editor on my laptop through MobaXTerm, the new file is always CRLF. I generally then just simply change it to LF as it's what's most compatible with Linux.
