### ISSUE TITLE
[21pt] Python package updates

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1227]
We are close to merging PR [1217](https://github.com/NOAA-OWP/inundation-mapping/pull/1217), which updates OpenJDK, adds some new packages and updates others.  

Some of the notable upgrades in 1217, is numba, numpy and xarray. For 1217, those packages have been tested heaviliy and are just fine.

However, a run of `pipenv check` which reveals vulnerabilities found:
aiobotocore
fiona
jinja2
pyogrio
pyproj
rasterio

It would also be wise to look into other major packages in our use such as pandas, geopandas, pyarrow, and shapely

Please wait until PR 1217 is merged before addressing these. I don't believe they are urgent but keep on the radar.

---------------
Update: Aug 9, 2024
Please update boto3 as well. :)  Updating boto3 will likely fix aiobotocore above, but not sure.

**Comment by mluck** [comment]
Upgrading geopandas from v0.14.3 to v1.0.1 introduced the following (in v1.0.0), requiring some fixes in our repo:

Backwards incompatible API changes:
The sjoin method will now preserve the name of the index of the right
GeoDataFrame, if it has one, instead of always using "index_right" as the
name for the resulting column in the return value.

**Comment by mluck** [comment]
This will address #1249 (see https://github.com/NOAA-OWP/inundation-mapping/pull/1249#issuecomment-2284479701).
