### ISSUE TITLE
[8pt] GMS catchment being dropped

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1280]
Looking at the new HAND v4.5.2.11 in the staging server I've seen a couple of locations where it appears that GMS is not running correctly. The screenshot below is from the Sabin River @ Orange, TX (HUC `12010005`). HAND v 4.4.0.0 is on the left and v4.5.2.11 is on the right.
![Image](https://github.com/user-attachments/assets/a5663f04-383f-4e1f-b7cc-04d5a6446a45)

Upon inspection of the v4.5.2.11 data, branch `1477000010` is missing some catchments. I suspect they are being dropped because of the new crosswalking algorithm that drops catchments if it can't snap to a streamline within 100m.
![Image](https://github.com/user-attachments/assets/bad64415-6199-4e12-a29e-ec1a03f21332)

The places I've seen where this is happening seems to be isolated to areas near the coast and seems to be fairly uncommon.

**Comment by mluck** [comment]
There are a couple of things going on here.

1. This HUC's outlet levelpaths (colored lines) drain into a lake (shaded blue) in the downstream HUC. Although the original NWM streams (blue lines) do extend past the DEM into the lake, because we clip levelpaths in lakes, the outlet levelpaths don't reach the edge of the DEM (shaded green) and cause reverse-flow issues upstream. The dashed black lines are DEM-derived reaches for branch 0 and the direction of flow is from the east along the yellow levelpath and out through the orange levelpath to the north.
![image](https://github.com/user-attachments/assets/ddfde426-30ce-43cc-b19f-006da25b511e)

2. The interaction between reverse flow and pit filling as well as the lack of spatial cohesion between the NWM streams and the channel in the DEM is causing deviations in DEM-derived reaches. Here, the branch 0 reaches (black dashed line) follows the burned in NWM levelpath (purple line). However, the branch 1477000010 line (solid red) more closely follows the depression in the DEM and as suggested in the original issue post above, results in the reach being over the 100m distance used to snap the crosswalk from the NWM stream and so that reach and its catchment are dropped.
![image](https://github.com/user-attachments/assets/b7de082d-b450-4ece-9ac5-aeb8d69115e5)

**Comment by mluck** [comment]
I created a patch to remedy the issue above that doesn't clip levelpaths in waterbodies outside of the HUC. But during testing found another issue related to the input data, that there is more than one "outlet". There is a canal (red line) that exits the HUC to the east, and since it's an outlet it isn't clipped. Both are being used by branch 0 as the outlets of the HUC. 
![image](https://github.com/user-attachments/assets/843ff97f-687d-496a-a458-c5c6e1580a90)

**Comment by mluck** [comment]
The patched DEM-derived reaches (blue line) fills in the branch 1477000010 reaches that were previously missing (the sections between the red dotted lines), including the original issue (A) and the downstream portion (B).
![image](https://github.com/user-attachments/assets/1e0d294c-2dc8-4066-9969-de31cbc071e5)

**Comment by mluck** [comment]
Here's the difference in catchments for branch 1477000010 (v4.5.2.11 catchments in brown, additional new catchments in purple). The yellow line is the old (v4.5.2.11) levelpath and the blue is the new levelpath.
![image](https://github.com/user-attachments/assets/581e4560-22c3-462c-949e-ed8b780875fa)

**Comment by mluck** [comment]
This is the difference in inundation with a 10 year recurrence flow.

v4.5.2.11
![image](https://github.com/user-attachments/assets/c54b0148-539a-4d48-b99e-f612345b0145)

new
![image](https://github.com/user-attachments/assets/2d167ae0-e3b1-4880-b4ff-18756df7a64d)
