### ISSUE TITLE
[8pt] Trim DEM derived streamline so that it does not extend past the NWM flowline

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#560]
Due to the nature of GMS modeling each level path separately, inundation will often travel downstream of confluences. After catchments are delineated in `run_by_branch`, we need to remove catchments that do not intersect with the branch flowline.

**Comment by RobHanna-NOAA** [comment]
Ya.. I believe this fix would take care of some of my errors which I now trap as well (from a recent upgrade in logging).

**Comment by RyanSpies-NOAA** [comment]
Here is an example where inundation mapping downstream of a tributary can lead to issues/errors. The screenshot below shows the benchmark evaluation for HUC 07080101. Note that there is no benchmark data (flow and inundation extent) available for the mainstem Mississippi River; however, the FIM4 solution is producing inundation all along the mainstem river (see red false positive extent).
![image](https://user-images.githubusercontent.com/69868854/166519067-b89487c8-fc00-4530-b2d6-ba208e60b7ea.png)

**Comment by JamesColl-NOAA** [comment]
Notes from tagup:
- After the hand is generated, the catchments need to be intersected with the (dissolved) branch segments.  Those catchments which don't intersect need to be deleted.
- Tailwaters which end in a junction should be split to avoid including extended catchments from branches which join upstream (look to [split_derived_reaches](https://github.com/NOAA-OWP/inundation-mapping/blob/43bcf4901802a39eff07b05910f02e3e9975be2d/src/gms/run_by_branch.sh#L180)with split_flows.py)
- Clarification:
  - HydroID is unique to catchment and dem_derived_stream segment
  - featureID from NWM
  - These two are conflated/rectified in [add_crosswalk.py](https://github.com/NOAA-OWP/inundation-mapping/blob/605b95a6bf389a165c263c1e02a841bcaf31f9b5/src/add_crosswalk.py)

**Comment by CarsonPruitt-NOAA** [comment]
@JamesColl-NOAA I just want to document the new strategy that we discussed. Instead of trimming catchments, we're now going to trim the DEM derived streams that come out of streamnet. Here's the logic you'll need to follow:

1. Load the dissolved level paths GPKG and get the coordinates of the terminal vertex
2. Snap those coordinates to the nearest point on the DEM derived streams [this process is also done [here](https://github.com/NOAA-OWP/inundation-mapping/blob/235268fc6c3af1765a280df63004b3f0a626c794/src/usgs_gage_unit_setup.py#L67])
3. Trim the portion of the DEM derived stream that's downstream of the snapped point

Let me know if you need any clarification.

**Comment by CarsonPruitt-NOAA** [comment]
@JamesColl-NOAA VS code is telling me that `nwm_streams_filename` on lines 82 and 85 is not defined. Maybe you've seen that bug and just haven't pushed it yet?

**Comment by JamesColl-NOAA** [comment]
Thanks for that catch, it would help if I attached the image to the right repo at build time.  Corrected and streamline version pushed up to that branch.

**Comment by RobHanna-NOAA** [comment]
I am trying a couple hucs with the issue in a before/after model. Running it once against dev branch to get the tifs and rem's, then again with Jim's code so I can compare them. Might take a bit but should help validate the fix.
