### ISSUE TITLE
[3pt] Ensure that the 3DEP domain covers the same area as our FIM v3 NHDHR DEMs

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#714]
Since we're changing over to a new source for our DEMs, I want to make sure that they are covering the same domain – specifically along the US - Texas border on the Mexican side.

Let's also check a couple of places along the Canadian border as well.

**Comment by RobHanna-NOAA** [comment]
Using the new adjusted included_hu8.lst, I loaded that as a table into QGIS, left joined it to the WBD HUC8 table, filtered out the nulls (for huc8's that are not on the list), and viewed the outputs. It showed that all areas in CONUS are now covered. Not, this is less area than FIM3 and that is because we are no longer processing data outside the US borders.
