### ISSUE TITLE
[8pt] Add south Alaska to HAND processing

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#792]
A list of south Alaska HUCs is coming and need to be included in our BED runs.

All inputs should be there, but this card is to prove that those HUCs will process correctly.

Even the final FIM BED results for the Alaska HUCs need to remain as EPSG:3338. 

- A separate PR, [1028](https://github.com/NOAA-OWP/inundation-mapping/issues/1028),  has been created to get the 3Dep DEM's via the acquire scripts. If other additional inputs are required for Alaska, those will also be covered by the other PR. 
- A separate PR, [1033](https://github.com/NOAA-OWP/inundation-mapping/issues/1033):  Add South Alaska to pre-clip vectors system has been added recently. Not yet sure if this can be pre-done before HAND integration but will try.

Other tasks required:  (note.. key sub-tasks can be listed here if required. Big ones can likely go to their own PR depending on size and inter relationship of the tasks.
- Update included_huc8.lst to include the selected new South Alaska HUCs.

**Comment by RobHanna-NOAA** [comment]
Ok. no problem. Emily.. I can start getting you the DEM's and pick up where we left off

**Comment by CarsonPruitt-NOAA** [comment]
Yes, we will want to store the Alaska data as 3338. Rob, I think it would be best for you to get the data set up and then Emily can work out the kinks from there.

**Comment by RobHanna-NOAA** [comment]
@EmilyDeardorff : Can you figure out what HUC8's are now going to be used for Alaska?  As Carson mentioned it will be the HUC 2 of 19 (HUCs starting with 19), but we don't need all of Alaska. Only the HUCs 8 that we have NWM stream data for.

**Comment by CarsonPruitt-NOAA** [comment]
Liliana probably also knows which HUCs are the ones we need for Alaska covered by NWM v3.

**Comment by EmilyDeardorff** [comment]
The HUC8_Alaska_NWMv30 shapefile that Alemayehu sent us on Sept 22 contains these HUCs: 19020202, 19020301, 19020602, 19020203, 19020302, 19020800, 19020201, 19020104, 19020601, 19020401, 19020103, 19020402, 19020505, 19020503, 19020504, 19020102, 19020101, 19020502, 19020501

Does that look right?

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/c00d5042-4129-4cb1-9308-debb9b659c3d)

**Comment by RobHanna-NOAA** [comment]
oh  ya. Can you compare those HUCs to the streamlines and makes sure it matches?  But yes, I think that has it. I will work this week on getting you some DEMs in 3338 for those HUCs.

**Comment by EmilyDeardorff** [comment]
**'Lake' column issue (2/28/24)** 

The NWM streams geopackage did not have the 'Lake' attribute like it was supposed to. It turns out that data was there, just in a column titled 'NHDWaterbodyComID'. To resolve, I created a column called 'Lake' in the NWM streams Alaska geopackage (which is an input to the pre-clip processing).  

**Incorrect CRS for Alaska (2/28/24)**

The default FIM projection is not correct to use for Alaska. To resolve, I added logic to a few scripts to assign the CRS variable depending on whether it is an Alaska HUC or not.

**DEM domain geopackage not matching Alaska CRS (2/29/24)**

The input DEM domain (`input_DEM_domain=${inputsDir}/3dep_dems/10m_5070/HUC6_dem_domain.gpkg`) was not a compatible CRS with the Alaska data (even though the polygon does include Alaska). To resolve, I added logic to a few scripts that uses the Alaska DEM domain (`inputs/3dep_dems/10m_South_Alaska/23_11_07/DEM_Domain.gpkg`) if the Alaska HUC is detected.

**Comment by EmilyDeardorff** [comment]
**Future Work: Need to get USGS gages for Alaska (3/4/24)**

With the recent in the `dev-fim-pipeline-alaska` branch, the FIM pipeline has run to completion for the first time. Most of the outputs look as expected, with the exception of some USGS outputs (listed below). This is to be expected because our inputs do not currently contain the USGS gages for alaska. Eventually, we will want to add another USGS gages file that contains that data for Alaska.

---

FIM pipeline outputs summary:

 - HUC folder is missing:
    - usgs subset gages
    - usgs subset gages 0
    - usgs elev table
    - 3d nld subset levees burned

- branch 0 folder is missing: 
   - usgs elev table

- branch folder is missing:
   - usgs elev table

**Comment by EmilyDeardorff** [comment]
**Branch Zero Inundation of the Matanuska River near Palmer, Alaska**

- input flow for every branch was set to 890 CMS, which is the 20% AEP flow for the Matanuska R at Palmer AK USGS gage
- the cross-hatched area marks the boundary of HUC 19020402
- mosaic or branch inundation is not included in this image


_Branch zero inundation near the Matanuska River at Palmer AK - [USGS gage 15284000](https://waterdata.usgs.gov/monitoring-location/15284000/#parameterCode=00065&period=P7D&showMedian=false)_
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/e3e72c76-8ff7-46e3-8fa7-333f4a984c59)

**Comment by EmilyDeardorff** [comment]
**High stream density leading to too many branches in HUC 19020402**

Running the FIM pipeline on HUC 19020402 (Matanuska River near Palmer, Alaska) resulted in 867 branches being generated. The expected number of branches for a HUC is more like 20-40 branches. This unexpected behavior can be attributed to an overly dense network of streams being fed into the model. The figures below shows that the intensity of this issue varies between HUC.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/b2cdf19d-645e-4e8d-8620-e43a544c2826)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/113335d4-3e49-4620-83ca-e92be18f9884)

**Comment by EmilyDeardorff** [comment]
**50% AEP Alaska inundation after mitigating stream density issue**
These results are using preliminary AEP flow data.


![matanuska_river_palmer_50AEP](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/44b7ea45-0421-480b-a8e9-4058d5e00ef5)
_Matanuska River near Palmer, AK_

![eagleriver_50AEP](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/7a827d40-1c07-4a86-9c46-dabc597ea8f3)
_Eagle River, AK_

![anchorage2_50AEP](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/d9c189e4-8984-4637-9bfa-538fc5b487de)
_Anchorage, AK_

![anchorage_50AEP](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/8cb3a738-5d12-4715-8949-8671727379b8)
_Anchorage, AK_

![trapper_creek_50AEP](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/5a1b289a-1694-405f-a4f8-cec46f4c30c5)
_Trapper Creek, AK_

![rude_river_50AEP](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/f59846c0-05aa-494a-bcf6-df9ba1d83ae5)
_Rude River, AK_
