### ISSUE TITLE
[8pt] Change all phrases of "data/outputs" to "/outputs"

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#813]
The docker volume mount for "outputs" is not being used much as most sections of code are using "data/outputs" instead of "/outputs". This results in code using the docker "data" volume mount instead of the "outputs" volume mount.

**Comment by robgpita-noaa** [comment]
From @mluck: " I have a suggestion/request: as `/data/outputs` gets changed to `/outputs`, note that there is an instance of this in the README that needs to be changed under Produce HAND Hydrofabric. Then I realized that we don't (but should) have the docker run command on that page that would go immediately before or as the first item after [Produce HAND Hydrofabric](https://github.com/NOAA-OWP/inundation-mapping/blob/dev/README.md#produce-hand-hydrofabric) otherwise none of the commands below that will be able to be run."
