### ISSUE TITLE
[13pt] Levees are masking too many areas

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#822]
The stream-order-based method for masking levees masks too many branches. I suggest using the following logic to join levee protected areas to their levee polylines and then using the polylines to determine which branches should get masked. Obviously, this is just a suggestion -- feel free to change it up if you have a different workflow that might work better. 

1. Acquire all levee polylines. Currently, we filter out the levees that do not have elevation data tied to them.
    - Change the levee burning module to filter the levees without elevation data since we're no longer doing it in the acquisition step.
2. For each HUC, clip both the levee polylines and levee protected areas to the WBD boundary.
3. For each levee protected area (polygon) within each HUC:
    - Use the `systemId` field to find which levee lines are associated with the selected area.
    - If a protected area has no associated lines, do not mask any branches (this levee protected polygon may be protected against a river in an adjacent HUC, not the current one).
    - For each associated levee line, find the nearest level path (`nwm_subset_streams_levelPaths_dissolved.gpkg`)
    - Levees sometimes protect against more than one level path, so many levee protected areas should have more than one level path assigned for masking.
    - If ANY levee lines intersect with a level path, that level path should be removed from the list of masked branches (this is for branches that flow behind levees - see HUC `08020401` in second screenshot for an example).

HUC `08020302` - Levee in adjacent HUC is incorrectly masking
![image](https://user-images.githubusercontent.com/90792257/219820416-c96d5072-d267-4268-ab2d-4149e46e3d0e.png)

HUC `08020401` Branch `1533000005` - This is correct inundation within a protected area that we would like to keep in the upgraded algorithm.
![image](https://user-images.githubusercontent.com/90792257/219821211-5525c266-f95f-4ddf-9c9a-d0d04a48cabb.png)

This is a follow-up to the previous levee masking issue #759.

**Comment by mluck** [comment]
After looking at the data and talking with @CarsonPruitt-NOAA, the above workflow will need to be changed somewhat.

Step 1:
- [ ] Acquire all levee polylines -- has been completed (data downloaded from https://levees.sec.usace.army.mil/#/levees/search/in=@nation:USA&viewType=map&resultsType=systems&advanced=true&hideList=false&eventSystem=false)
- [ ] Change the levee burning module to filter the levees without elevation data since we're no longer doing it in the acquisition step.

Step 2:
- [ ] Clip to buffered HUC8 (wbd_buffered.gpkg) instead of the HUC8 boundary since the levee lines may be located on or near HUC8 boundaries and we want to make sure we retain them.

Step 3:
- [ ] Proposed solution:
- Buffer each side of levee line
- Intersect buffers with matching levee-protected area (and HUC8?)
- For each levee line:
    - Find level path(s?) on opposite side of levee-protected area
    - Mask branch(es?) of level path(s?)

**Comment by mluck** [comment]
I found a cleaner way to view and download the NLD levee data using a REST service: https://ags03.sec.usace.army.mil/server/rest/services/NLD2_PUBLIC/FeatureServer

**Comment by mluck** [comment]
> I found a cleaner way to view and download the NLD levee data using a REST service: https://ags03.sec.usace.army.mil/server/rest/services/NLD2_PUBLIC/FeatureServer

I was able to open the National Levee Database FeatureServer data in QGIS and save it from there, but then ran into a problem opening the file in Geopandas.

```
File fiona/ogrext.pyx:715, in fiona.ogrext.Session.get_schema()

File fiona/_geometry.pyx:81, in fiona._geometry.normalize_geometry_type_code()

UnsupportedGeometryTypeError: 2147483659
```

Turns out it seems to be a bug in Geopandas -- there's a workaround suggested in https://gis.stackexchange.com/questions/388167/opening-gkpg-in-geopandas-throws-unsupportedgeometrytypeerror-12 that uses Fiona to open the file and then Geopandas to read the Fiona features into a Geopandas GeoDataFrame that worked in this case.

**Comment by mluck** [comment]
There are a few edge cases that will require revisions to the new levee masking algorithm to work correctly. The current algorithm finds the closest level path to the levee but the issue is that the levee lines are often long and may span multiple level paths. A potential solution might be to split the levee lines to a max segment length like the reaches.

Example (single levee line in black, levee-protected areas in gray, level paths in color): In this case the purple branch would be masked but the mainstem branch (lime levelpath) would not be masked (but should be).

<img width="462" alt="image" src="https://user-images.githubusercontent.com/6616694/222479709-eaf0b917-5a9c-45e7-96de-45673d332ef9.png">

**Comment by CarsonPruitt-NOAA** [comment]
Is it possible to use your search buffer method to get _any_ intersecting level paths? So, in your example, lime purple, and possible pink will be masked.

**Comment by mluck** [comment]
Here's an update and examples of the algorithm as implemented so far.

### Correct
Levee-protected area unmasked where level path crosses a levee exactly once:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/6616694/224775261-98c6ee34-abea-43ea-892e-917f4b68708a.png">

The DEM for the blue levelpath which crosses more than once is masked:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/6616694/224818500-2de022ad-39ef-4812-9f43-935ef82f8e7e.png">

### Exceptions
The purple buffer associated with the interior of the levee (levee protected area in gray) is incorrect, probably because the large buffer size intersects the buffer with itself. This would seem to affect circular levee systems relatively small in relation to the levee buffer size. To address this case we may try to mask all level paths that intersect with either buffer.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/6616694/224835308-7ecbe8d1-2a28-4215-ad11-348b44205fbe.png">

Along the same line, there is also the possibility that for a concave section of a levee, the level path search buffer will extend into (and possibly beyond) the levee protected area of the same levee and identify level paths behind the levee. Masking levee-protected areas from the level path search buffer would probably help but might not be a sufficient solution.

**Comment by mluck** [comment]
To deal with the first exception above, I'm thinking that it might be better to start with a smaller buffer that works to correctly identify the levee protected area side of the levee, then if no level paths are found on the opposite side, then increase that buffer by a factor of 2x or 3x (or iteratively until a level path is found?).

**Comment by CarsonPruitt-NOAA** [comment]
Yes, that's definitely a viable solution. I'm thinking that 2km should probably be the max search distance, though.

**Comment by CarsonPruitt-NOAA** [comment]
Here's my part for the changelog/PR:

```
### General or Notes section:
There are now going to be two different levee vector line files in each HUC. One (`nld_subset_levees_burned.gpkg`) for the levee elevation burning and one (`nld_subset_levees.gpkg`) for the levee-level-path assignment and masking workflow.

### Additions:
- `data/`
    - `esri.py`: Class for querying and downloading ESRI feature services.
    - `nld/`
        - `levee_download.py`: Module that handles downloading and preprocessing levee lines and protected areas from the National Levee Database.

### Changes:
- `src/`
    - `clip_vectors_to_wbd.py`: Added the new levee lines for the levee-level-path assignment and masking workflow.
    - `run_unit_wb.sh`: Added inputs to `clip_vectors_to_wbd.py`.
    - `burn_in_levees.py`: Removed the unit conversion from feet to meters because it's now being done in `levee_download.py`.

### Notes:

- Usage for the new levee download workflow is simply: `python /data/nld/levee_download.py`. There will be 3 outputs written to `/data/inputs/nld_vectors/`. Whenever levees are updated, `/src/bash_variables.env` should also be updated to reflect the new filenames since the dates will be updated.
    - `System_Routes_NLDFS_5070_{YYMMDD}.gpkg`
    - `3d_nld_preprocessed_{YYMMDD}.gpkg`
    - `Leveed_Areas_NLDFS_5070_{YYMMDD}.gpkg`
```

The new `levee_download.py` module probably deprecates `/data/nld/preprocess_levee_protected_areas.py` since the download script handles all of the reprojection and saving to a geopackage. I recommend removing this file from the repo.

**Comment by CarsonPruitt-NOAA** [comment]
@derekgiardino found this levee in HUC `03140202` that has some levee inundation. Please add this to your testbed.

![image](https://user-images.githubusercontent.com/90792257/225147447-107b5155-959a-4084-a2b7-09540e1a501b.png)

**Comment by mluck** [comment]
All of the REMs (branches 0, 1, 18, and 19) are now masked so they should not show any inundation with this revised method.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/6616694/225408899-b57cc450-eeca-45f1-835c-916234176d51.png">
