### ISSUE TITLE
[5pt] CatFIM sites are sharing the same LID

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#831]
There are 4 CatFIM sites in HUC `18070102` that all have the same LID. `srfc1`, `scpc1`, and `sesc1` all have `vcac1` listed incorrectly as the LID field.

**Comment by LauraKeys-NOAA** [comment]
Is this an error that's showing up in the services?

**Comment by CarsonPruitt-NOAA** [comment]
Yes, I haven't checked our data.

**Comment by LauraKeys-NOAA** [comment]
Okay, further info on this error.. flow-based CatFIM for version 4.0.13.1 is showing this. The sites themselves have the right LIDs, but the associated polygon layers are all tied to VCAC1 (and they're all along the Santa Clara River). Oddly, the flow values for all the stages above action are listed as 0, and action is 70000 cfs, though there are polygons showing up for them. Looking into this more in the gpkg files.

**Comment by LauraKeys-NOAA** [comment]
I tracked this error down. It was showing up in our gpkg files. When I ran VCAC1 and SRFC1 together, SRFC1 would receive the wrong LID, but when I ran SRFC1 alone, it was fine. There was a list of tiffs to reformat that wasn't getting reset each time at the start of a loop, and it was causing the VCAC1 site info to get transferred to the other sites that were processed in the same HUC after it. This error likely affected other sites too, but the fix is simple. Doing another test just to verify before I include it in a PR.
