### ISSUE TITLE
[8pt] Update the alpha test to accept previous runs' metrics CSV

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#838]
As part of our AWS transition, the alpha test needs to accept previous alpha test CSV files. This should be a new optional argument to `tools/synthesize_test_cases.py` that when passed,  should override the need to scan the other `test_cases` directories.

The new aggregated hydroTable should also be added to this workflow. I believe this change will need to be in `tools/run_test_case.py`. #836

**Comment by CarsonPruitt-NOAA** [comment]
FYI You can use `/data/test_cases/metrics_library/fim_4_x_metrics.csv` as a test input.

**Comment by CarsonPruitt-NOAA** [comment]
We should also warn the user if they do not supply a previous metrics CSV.

**Comment by RyanSpies-NOAA** [comment]
Discussing this out loud with Emily, we came up with a couple of thoughts/ideas that would be good to get other opinions on (@CarsonPruitt-NOAA, @BradfordBates-NOAA, @RobHanna-NOAA):
- Seems like a good idea to maintain the functionality for `-dc` flag where a user would want to compare their current development metrics to a past development version that they have access to. This assumes that the user has the `-dc` outputs available in their local `test_cases\.\.\testing_versions`. I definitely use this functionality when comparing a bunch of different development versions against each other.
-  We are going to scrub the current code for anything dealing with `previous_fim` and `official_versions` because those outputs will likely not be accessible in the user's `test_cases` directory when running in AWS. We will replace this functionality with a new optional input argument (`-prev`) where the user can provide a csv file that contains any previous metrics to concatenate with the new metrics to form a final aggregated metrics csv.
- Thoughts on having the code produce two csv files whenever the user provides a valid input variable using the `-prev` argument? 
  - The first output csv would include all of the metrics generated for the current fim version (`-v`) as well as any dev compare metrics if the user provides the `-dc` arg. I propose we name this csv: `-v` + "_metrics.csv"
  - If the user provides the new (optional) input arg (`-prev`) for the "previous_metrics_csv", a second output csv would be created and include everything in the first csv as well as all of the metrics in the previous metrics csv file. I propose we name this csv: `-v` + "_aggregate_metrics.csv"

**Comment by CarsonPruitt-NOAA** [comment]
I like all of these suggestions. The 2-csv output also jives with the near-future update to the test_cases folder where the version will be the top-level directory and the first, version-specific csv will be stored in that directory.

**Comment by BradfordBates-NOAA** [comment]
I agree, it all sounds reasonable.

**Comment by RobHanna-NOAA** [comment]
Love it.
