### ISSUE TITLE
[13pt] Docker - update base osgeo image

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#840]
Our current docker image is built against osgeo/gdal:ubuntu-full-3.1.2. and is over 3 years old. ITSG wants us to upgrade base images. The most current available (as of Mar 6, 2023) is osgeo/gdal:ubuntu-full-3.4.1.  We need to get it upgraded.

Note: a number of packages and their versions will likely be upgraded. We can eval all of our python packages to see if some are not included (or upgraded) in the base image. 

While the fix may be easy, the eval of packages may take a while. There is info that upgraded to base images are known to be bumpy, so we need to allocation a fair bit of time, just in case. 

A recent other issue has been added for upgrading pandas and reviewing other packages [issue 864](https://github.com/NOAA-OWP/inundation-mapping/issues/864) An upgrade of the base osgeo image, might auto upgrade some of these packages and need to be reviewed.

**Comment by mluck** [comment]
The current `dev` base image is `osgeo/gdal:ubuntu-full-3.1.2`. So far I've been able to successfully upgrade GDAL to v.3.4.3. All Python packages have been upgraded to latest versions as well, notably Pandas to v.2.0.0.

The latest base image is `ghcr.io/osgeo/gdal:ubuntu-full-3.6.3`, but starting with 3.6.0 the base image for that was upgraded from ubuntu 20.04 to 22.04 which upgraded Python from v.3.8.10 to v.3.10.6.

## Important Notes
- Starting with GDAL version 3.2, GDAL needs to be imported as `from osgeo import gdal` rather than `import gdal`.
- Pandas has also been upgraded to v. 2.0.0 which deprecates and changes a few things (these have been fixed in the current branch):
    - `pd.DataFrame.append()` has been deprecated: replace with `pd.concat()'
    - `float/int(Series[single_element])` has been deprecated: replace with `float/int(ser.iloc[single_element])`

**Comment by mluck** [comment]
It looks as though something introduced in GDAL version 3.5 changes the output of TauDEM's `aread8`. I ran `aread8` using the same code and data, with only the base GDAL image being different (ghcr.io/osgeo/gdal:ubuntu-full-3.4.3 vs ghcr.io/osgeo/gdal:ubuntu-full-3.5.3). In the following images of `flowaccum_d8_burned_filled`, green=1, blue=0, and white=nodata.

GDAL v3.4.3
<img width="329" alt="image" src="https://user-images.githubusercontent.com/6616694/232592039-cea213c6-681e-405a-a9f6-14fd259f6462.png">

GDAL 3.5.3
<img width="329" alt="image" src="https://user-images.githubusercontent.com/6616694/232592266-68e209c0-7656-4155-9e91-b2b29a8ef8d6.png">
