### ISSUE TITLE
Add line breaks and/or incorporate linting

### ISSUE THREAD

**Issue by robgpita-noaa** [NOAA-OWP/inundation-mapping#846]
Incorporating the use of a code linter would greatly benefit the layout and formatting of this repository.

In the absence of a linter, breaking up long lines of code should be tackled for readability's sake. 

## Current code

No line breaks exist in many bash scripts and python files. This proves difficult to read, understand, and modify arguments passed. 

## Expected code

An attempt should be made to adhere to the [PEP-8 Standard](https://peps.python.org/pep-0008/#:~:text=The%20Python%20standard%20library%20is,inside%20parentheses%2C%20brackets%20and%20braces.) of 79 characters (docstrings/comments to 72). 

While there is no definitive style guide for Shell Scripts, the [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html#s5.2-line-length-and-long-strings) can be used a starting point.

**Comment by mluck** [comment]
Agreed  -- see #194 (and #34) for previous discussions on this.

**Comment by RobHanna-NOAA** [comment]
Yes, PEP8 suggests 79 chars. I find that excessive and generally aim for 110 (ish)

**Comment by RobHanna-NOAA** [comment]
Maybe we just need an email to the team on how to install and use it as well as bring awareness to PEP-8.  There are so many standards that we can't ask our team to learn them all now, but we can start looking for the big ones, like max line length, I recommend 110 or 120 instead of 79.  I think people don't know about different ways to use line breaks, be it a method/function all, text string, params, etc. Some examples might be helpful.  I also recommend we ensure they are using a space after a comma as that is a big readability issue. Overall.. the theme should always be "readability" for others. Inline notes, line breaks, spacing, organizing imports, etc.
