### ISSUE TITLE
[5pt] Whitebox issue tracker

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#863]
Adding this card so we can keep track of everything associated with this issue.

**Comment by CarsonPruitt-NOAA** [comment]
[Submitted an issue with Whitebox Tools](https://github.com/giswqs/whitebox-python/issues/56)

**Comment by RobHanna-NOAA** [comment]
I did last night and got a response:
`From: Qiusheng Wu <notifications@github.com>
Sent: Tuesday, March 28, 2023 6:19 PM
To: giswqs/whitebox-python <whitebox-python@noreply.github.com>
Cc: Rob Hanna <ColoradoJake1@hotmail.com>; Author <author@noreply.github.com>
Subject: Re: [giswqs/whitebox-python] whitebox_tools requires GLIBC 2.32 or higher (Discussion #55)

 

It is because pip install whitebox will always pull the latest WBT backend from the whitebox.com server at this url https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_amd64.zip. It does not matter what pip whitebox version you install, the program will always pull the latest WBT backend from this same url. I am not sure if @jblindsay keeps a copy of the old version WBT on the whitebox.com server.

One temporary solution is that you pull the WBT backend from the URL below. It is the one I built using Ubuntu 18.04 with an older version of GLIBC so that users can use it with Google Colab. In your docker, you download this zip file and unzip it to your whitebox package installation directory, e.g., python3.x/site-packages/whitebox/whitebox_tools
https://github.com/giswqs/whitebox-bin/blob/master/WhiteboxTools_ubuntu_18.04.zip

**Comment by RobHanna-NOAA** [comment]
whitebox 2.3.1 works.  I will put a code fix in shortly which we can merge and distribute to folks.  And for the next few days only, when they start a container, they simply run `pip install whitebox==2.3.1`.  I can go into the shapeply branch, update the pipfile and pipfile.lock for whitebox 2.3.1 and we should be set for a new docker build on Friday.

**Comment by RobHanna-NOAA** [comment]
While still being 100% validated.. the interium solution for developers is to open a docker container and run

 `pip install whitebox==2.3.1; wbox_path=/usr/local/lib/python3.8/dist-packages/whitebox/ ; wget -P $wbox_path https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_musl.zip ; unzip  -q -o $wbox_path/WhiteboxTools_linux_musl.zip -d $wbox_path ; cp $wbox_path/WBT/whitebox_tools $wbox_path ; mkdir $wbox_path/testdata`

This will get them up and running.

We will make a docker file and pip change to make the fix permanent.
