### ISSUE TITLE
[5pt] fim_4_3_5_0 branch errors

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#869]
During the BED run of fim_4_3_5_0, eight branches threw and error (all of same type). No HUCs were in error, so I continued the build process.

The error: 
	----------------------------------------------------------------
	Sample reach averaged parameters 01100003 6141000003
	Sat Apr  1 20:55:38 UTC 2023
	CatchHydroGeo version 5.3.9
	Input file /fim_temp/fim_4_3_5_0/01100003/branches/6141000003/rem_zeroed_masked_6141000003.tif has projected coordinate system.
	This run may take on the order of 1 minutes to complete.
	This estimate is very approximate. 
	Run time is highly uncertain as it depends on the complexity of the input data 
	and speed and memory of the computer. This estimate is based on our testing on 
	a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
	Nodata value input to create partition from file: -999999.000000
	Nodata value recast to float used in partition raster: -999999.000000
	Input file /fim_temp/fim_4_3_5_0/01100003/branches/6141000003/gw_catchments_reaches_filtered_addedAttributes_6141000003.tif has projected coordinate system.
	Nodata value input to create partition from file: 0.000000
	Nodata value recast to int32_t used in partition raster: 0
	Input file /fim_temp/fim_4_3_5_0/01100003/branches/6141000003/slopes_d8_dem_meters_masked_6141000003.tif has projected coordinate system.
	Nodata value input to create partition from file: -999999.000000
	Nodata value recast to float used in partition raster: -999999.000000
	ERROR: catch list empty!

Branches involved:
		01100003_branch_6141000003.log
		02030203_branch_7733000010.log
		02080104_branch_8479000032.log
		03010102_branch_8653000058.log
		08020204_branch_3671000004.log
		10260005_branch_1894000001.log
		12070203_branch_5592000001.log
		18010105_branch_2702000035.log

**Comment by mluck** [comment]
So far I've looked at a couple of these (01100003 and 02030203) and they are both coastal branches with some odd features. Mainly, the levelpath (blue) for each of the branches extends into the LandSea mask (light blue). The routine that is failing is catchhydrogeo from TauDEM because the one of the inputs (`gw_catchments_reaches_filtered_addedAttributes_`) is invalid. This comes from `filter_catchments_and_add_attributes.py` when `output_catchments` is empty.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/6616694/230674536-b03f683e-6eff-462b-8cb4-74b13cfab3c1.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/6616694/230674731-6e2ba5d5-79f6-47e2-943b-681a4f334c92.png">
