### ISSUE TITLE
[8pt] VLab #116189: Potential hydrofabric issues on Arkansas River - CO

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#905]
https://vlab.noaa.gov/redmine/issues/116189

Maybe related to #811?

**Comment by mluck** [comment]
It seems that #903 (v4.3.11.0) fixed this.

Previously, inundation (shown with 25 year recurrence flow) was mis-routed from the mainstem to the side channel
<img width="733" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/fb3b656a-791b-4f61-9f2a-c7523edfeaf3">

With v4.3.11.0, inundation now correctly follows the mainstem. There is still some inundation on the side channel because it is a 4th order stream so not subject to being excluded by #903.
<img width="733" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/87c92d7e-eb35-4e5f-a1b2-e996a5246ba1">

The Vlab ticket has been updated with this information.
