### ISSUE TITLE
[8pt] Panda and GeoPandas Warnings

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#947]
In the unit logs, which includes a bunch of branch logs as well, there are a number of warnings that should be addressed. They are taking up a large amount of log volume but irrespective of that, should be fixed either way.

Look at a unit log for more details and tracing

Here are couple of types of warnings:

1) 
```
/foss_fim/src/stream_branches.py:503: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  if int(tmp_self.To_Node[tmp_self.From_Node.astype(int)==upstream_ID]) in nonlake_reaches:
```
  
2) 
```
/foss_fim/src/stream_branches.py:507: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_self.drop(tmp_self[tmp_self.From_Node.astype(int).isin([upstream_ID,])].index, inplace=True)
```

3) 
```
/foss_fim/src/split_flows.py:55: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  nearest_index = int(sjoin_nearest['LINKNO'])
```

**Comment by mluck** [comment]
The first and third warnings in this issue are fixed by changing `ser.astype(int)` or `int(ser)` (where `ser` is a single element pandas.Series) to the form `int(ser.iloc[0])`, for example, changing `if int(tmp_self.To_Node[tmp_self.From_Node.astype(int)==upstream_ID])` to `if int(tmp_self.To_Node[int(tmp_self.From_Node.iloc[0])==upstream_ID])`. However, if the length of `ser` is variable (e.g., may depend on the number of lakes in a HUC), the case where `len(ser)==1` may need to be treated separately from where `len(ser) > 1`.

The second warning was a bit more tricky and uncovered a push to avoid using `inplace=True` in most cases (including the example in 2). See [here](https://github.com/pandas-dev/pandas/blob/57390ada100466dac777e5b66d5a4f2a72700c38/web/pandas/pdeps/0008-inplace-methods-in-pandas.md) for explanation/documentation. To summarize, the list below includes the Pandas functions in which `inplace=True` is unnecessary and can (or should) be avoided:
align
astype
concat
drop
dropna
drop_duplicates
infer_objects
query
reindex
reindex_like
rename
rename_axis
reset_index
set_index
sort_index
sort_values
set_axis
set_flags
swapaxes
swaplevel
to_period
to_timestamp
tz_convert
tz_localize
transpose
truncate

In contrast, `inplace=True` remains a valid argument for the following functions.
bfill
clip
ffill
fillna
interpolate
mask
replace
where

**Comment by mluck** [comment]
@RobHanna-NOAA Another thing that will reduce the size of the log files significantly would be removing the tqdm progress bars. For instance, the example below has 557 lines in the log file just for a single progress bar:

```
Split Derived Reaches 07140106 0
Tue Aug  1 19:38:35 UTC 2023
Loading data ...
trimming DEM stream to NWM branch terminus
splitting stream segments at HUC8 boundaries
splitting stream segments at 9 waterbodies
splitting 3532 stream segments based on 1500.0 m max length

  0%|          | 0/3532 [00:00<?, ?it/s]
  0%|          | 5/3532 [00:00<01:18, 44.94it/s]
  0%|          | 10/3532 [00:00<01:48, 32.60it/s]
  0%|          | 14/3532 [00:00<01:40, 34.92it/s]
  1%|          | 23/3532 [00:00<01:05, 53.17it/s]
  1%|          | 38/3532 [00:00<00:48, 71.67it/s]
  1%|▏         | 48/3532 [00:00<00:47, 73.73it/s]
  2%|▏         | 70/3532 [00:00<00:31, 110.35it/s]
  2%|▏         | 82/3532 [00:01<00:35, 96.65it/s] 
  3%|▎         | 93/3532 [00:01<00:36, 95.16it/s]
  3%|▎         | 103/3532 [00:01<00:41, 82.51it/s]
  3%|▎         | 117/3532 [00:01<00:37, 91.65it/s]
  4%|▎         | 128/3532 [00:01<00:35, 95.06it/s]
  4%|▍         | 153/3532 [00:01<00:25, 134.65it/s]
  5%|▍         | 168/3532 [00:01<00:32, 104.07it/s]
  5%|▌         | 181/3532 [00:02<00:31, 107.08it/s]
  5%|▌         | 193/3532 [00:02<00:45, 73.00it/s] 
  6%|▌         | 203/3532 [00:02<00:56, 58.77it/s]
  6%|▌         | 211/3532 [00:02<00:54, 61.23it/s]
  6%|▌         | 219/3532 [00:02<01:03, 51.90it/s]
  6%|▋         | 226/3532 [00:03<01:01, 53.68it/s]
  7%|▋         | 233/3532 [00:03<01:05, 50.37it/s]
  7%|▋         | 239/3532 [00:03<01:10, 46.38it/s]
  7%|▋         | 245/3532 [00:03<01:19, 41.17it/s]
  7%|▋         | 250/3532 [00:03<01:35, 34.37it/s]
  7%|▋         | 255/3532 [00:03<01:32, 35.25it/s]
  7%|▋         | 259/3532 [00:04<01:55, 28.44it/s]
  7%|▋         | 263/3532 [00:04<02:02, 26.63it/s]
  8%|▊         | 266/3532 [00:04<02:03, 26.34it/s]
  8%|▊         | 269/3532 [00:04<02:24, 22.62it/s]
  8%|▊         | 272/3532 [00:04<02:22, 22.95it/s]
  8%|▊         | 275/3532 [00:04<02:23, 22.73it/s]
  8%|▊         | 285/3532 [00:05<01:24, 38.43it/s]
  8%|▊         | 290/3532 [00:05<01:19, 40.95it/s]
  8%|▊         | 295/3532 [00:05<01:22, 39.35it/s]
  9%|▊         | 302/3532 [00:05<01:12, 44.29it/s]
  9%|▊         | 307/3532 [00:05<01:48, 29.78it/s]
  9%|▉         | 311/3532 [00:05<01:47, 29.89it/s]
  9%|▉         | 315/3532 [00:06<01:55, 27.91it/s]
  9%|▉         | 320/3532 [00:06<01:42, 31.45it/s]
  9%|▉         | 324/3532 [00:06<01:58, 27.08it/s]
  9%|▉         | 328/3532 [00:06<01:51, 28.75it/s]
  9%|▉         | 332/3532 [00:06<01:59, 26.85it/s]
  9%|▉         | 335/3532 [00:06<02:01, 26.38it/s]
 10%|▉         | 338/3532 [00:06<02:25, 22.02it/s]
 10%|▉         | 341/3532 [00:07<02:22, 22.33it/s]
 10%|▉         | 344/3532 [00:07<03:20, 15.88it/s]
 10%|▉         | 346/3532 [00:07<03:24, 15.59it/s]
 10%|▉         | 350/3532 [00:07<02:56, 18.04it/s]
 10%|▉         | 353/3532 [00:07<02:52, 18.45it/s]
 10%|█         | 362/3532 [00:07<01:38, 32.19it/s]
 10%|█         | 366/3532 [00:08<01:36, 32.82it/s]
 10%|█         | 370/3532 [00:08<01:49, 29.01it/s]
 11%|█         | 375/3532 [00:08<01:41, 31.18it/s]
```

**Comment by RobHanna-NOAA** [comment]
Yes... that would be super helpful as well. We just don't need the in AWS anymore.  Can  you look into that as well? Do you want a separate card for that one?

**Comment by mluck** [comment]
@RobHanna-NOAA Yeah, let's have a separate card for that. I think there's probably other things that can be cleaned up from the logs as well.

**Comment by robgpita-noaa** [comment]
@mluck & @RobHanna-NOAA, Issue #942 addresses the extra verbose logging.

**Comment by RobHanna-NOAA** [comment]
Ya.. good point Rob.  It might be smarter to leave progress bars for 942.
