### ISSUE TITLE
HydroVIS CatFIM Review

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#999]

**Comment by EmilyDeardorff** [comment]
I am currently working on Review 6, which can be found on the [CatFIM Review Google Sheet](https://docs.google.com/spreadsheets/d/1AxrgHvG-xF21uKd5wmDiJN6jYIfZuH_eEyyIJpzGCJQ/edit?usp=sharing). I am working through the sites in reverse order (compared to the other reviews) in order to ensure that we get eyes on more sites.
